#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# HS price service setup wizard.
# Spec: .scratch/hs-price-service/issues/01-setup-wizard.md
#
# Provisions everything the HS price service (and its spike) needs:
#   1. the published pantry-sheet CSV URL, verified and saved to .env
#   2. a persistent, authenticated Chromium profile for healthyselections.ca
#   3. proof the login works (a real item + price), via CDP
#
# The login session persists in the mounted volume under /config/profile
# (chromium --user-data-dir; an explicit non-default dir is required for CDP
# on Chromium 136+). The price service must launch chromium with the same
# --user-data-dir inside this mount.
#
# Re-running this wizard is the session-expiry re-login path. It is safe to
# interrupt: .env writes are idempotent upserts and the browser container is
# stopped on exit.

TOTAL_STAGES=3

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"

HS_WEB_PORT=3100            # web UI (KasmVNC), LAN-reachable while running
HS_CDP_PORT=9222            # CDP, localhost only
BROWSER_CONTAINER="hs-prices-login"
CHROMIUM_IMAGE="linuxserver/chromium:latest"
NODE_IMAGE="node:24.12.0-alpine"   # matches .tool-versions

BROWSER_STARTED=0
cleanup() {
  if [[ "$BROWSER_STARTED" == "1" ]]; then
    docker stop "$BROWSER_CONTAINER" >/dev/null 2>&1 || true
  fi
}
trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

# check_sheet_url URL fetches the published sheet and confirms it is CSV with
# an Item column. Prints a specific remedy for the two common paste errors.
check_sheet_url() {
  local url="$1" body header rows
  if ! body=$(curl -fsSL --max-time 30 "$url" 2>/dev/null); then
    warn "that URL didn't return anything (fetch failed)."
    return 1
  fi
  if [[ "$body" =~ ^[[:space:]]*\< ]]; then
    warn "that looks like an HTML page, not CSV."
    note "Use the 'Comma-separated values (.csv)' publish link — it ends in output=csv."
    return 1
  fi
  header=$(printf '%s\n' "$body" | head -n1)
  if ! printf '%s' "$header" | tr ',' '\n' | grep -qx 'Item'; then
    warn "the CSV has no 'Item' column — is this the AvailableAsOf view?"
    note "header row was: $header"
    return 1
  fi
  rows=$(printf '%s\n' "$body" | wc -l)
  printf '  %s✓%s CSV checks out — %s lines, Item column present.\n' "$GREEN" "$RESET" "$rows"
  return 0
}

banner "HS price service setup"

# ── Stage 1: capture the published pantry-sheet CSV URL ───────────────────
stage "Pantry sheet URL"
say "The menu builder reads the pantry sheet's AvailableAsOf view as CSV,"
say "published to the web."
say ""
say "If you don't have the link handy, publish it now in Google Sheets:"
step "File → Share → Publish to web"
step "Tab: AvailableAsOf · Format: Comma-separated values (.csv) → Publish"
step "Copy the link it gives you."
say ""
if ! command -v curl >/dev/null 2>&1; then
  warn "curl isn't installed on this machine; it's needed to check the URL."
  exit 1
fi
while true; do
  ask PANTRY_AVAILABLEASOF_CSV_URL "Paste the published CSV URL:"
  if [[ -z "$PANTRY_AVAILABLEASOF_CSV_URL" ]]; then
    warn "no URL pasted."
  elif check_sheet_url "$PANTRY_AVAILABLEASOF_CSV_URL"; then
    break
  fi
  confirm "Try again?" || { warn "aborted — re-run the wizard any time; nothing was changed."; exit 1; }
done
write_env PANTRY_AVAILABLEASOF_CSV_URL "$PANTRY_AVAILABLEASOF_CSV_URL"

# ── Stage 2: one-time Healthy Selections login ────────────────────────────
stage "Healthy Selections login"
if ! command -v docker >/dev/null 2>&1; then
  warn "docker isn't installed or not on PATH — the login browser runs in a container."
  exit 1
fi
if ! docker info >/dev/null 2>&1; then
  warn "can't talk to the Docker daemon (permission fix: sudo usermod -aG docker \$USER, then re-login)."
  exit 1
fi

HS_PROFILE_DIR="$REPO_ROOT/services/hs-prices/profile"
mkdir -p "$HS_PROFILE_DIR"

say "Starting a throwaway Chromium with a persistent profile volume."
note "First run downloads the browser image (~1 GB); later runs start in seconds."
docker rm -f "$BROWSER_CONTAINER" >/dev/null 2>&1 || true
docker run -d --rm \
  --name "$BROWSER_CONTAINER" \
  --shm-size=512m \
  -e "PUID=$(id -u)" \
  -e "PGID=$(id -g)" \
  -e "CHROME_CLI=--remote-debugging-port=9222 --remote-debugging-address=0.0.0.0 --user-data-dir=/config/profile https://healthyselections.ca/account/login" \
  -p "${HS_WEB_PORT}:3000" \
  -p "127.0.0.1:${HS_CDP_PORT}:9222" \
  -v "$HS_PROFILE_DIR:/config" \
  "$CHROMIUM_IMAGE" >/dev/null
BROWSER_STARTED=1

printf '  %swaiting for Chromium…%s\n' "$DIM" "$RESET"
cdp_up=0
for _ in $(seq 1 45); do
  if curl -fsS "http://127.0.0.1:${HS_CDP_PORT}/json/version" >/dev/null 2>&1; then
    cdp_up=1
    break
  fi
  sleep 2
done
if [[ "$cdp_up" != "1" ]]; then
  warn "Chromium didn't come up. Last container logs:"
  docker logs "$BROWSER_CONTAINER" 2>&1 | tail -n 15 || true
  exit 1
fi
printf '  %s✓%s browser is up.\n' "$GREEN" "$RESET"

lan_ip=$(hostname -I 2>/dev/null | awk '{print $1}')
say ""
say "On your phone (same wifi), open:"
printf '  %s%s  http://%s:%s%s\n' "$BOLD" "$GREEN" "${lan_ip:-<this-machine>}" "$HS_WEB_PORT" "$RESET"
say "  (or http://localhost:${HS_WEB_PORT} in a browser on this machine)"
say ""
step "You'll see a Chromium desktop, already on the HS login page."
step "Log into healthyselections.ca with the program's account."
step "Open any product and confirm you can see prices."
note "The web UI is reachable on your LAN only while this wizard runs."
note "If the login page didn't open, type healthyselections.ca/account/login"
note "in the browser's address bar."
say ""
confirm "Logged in, and prices visible?" || { warn "aborted — browser stopped, nothing half-set. Re-run any time."; exit 1; }

CHROME_CDP_URL="http://127.0.0.1:${HS_CDP_PORT}"
CHROME_WEB_URL="http://127.0.0.1:${HS_WEB_PORT}"
write_env CHROME_CDP_URL "$CHROME_CDP_URL"
write_env CHROME_WEB_URL "$CHROME_WEB_URL"
write_env HS_PROFILE_DIR "$HS_PROFILE_DIR"

# ── Stage 3: verify the login by reading the catalog ──────────────────────
stage "Verify access"
say "Proving the login works: reading the HS catalog through the profile"
say "and printing a real item and price."
note "First run downloads a small Node image (~50 MB)."
say ""
verify_out=$(docker run --rm --network host \
  -v "$REPO_ROOT/services/hs-prices:/work:ro" \
  -e "CHROME_CDP_URL=$CHROME_CDP_URL" \
  "$NODE_IMAGE" \
  sh -c "npm install --prefix /tmp/pw --no-audit --no-fund --loglevel=error playwright-core >/dev/null 2>&1 && NODE_PATH=/tmp/pw/node_modules node /work/verify-login.cjs" 2>&1) && verify_ok=1 || verify_ok=0
printf '%s\n' "$verify_out" | sed 's/^/  /'
say ""
if [[ "$verify_ok" != "1" ]]; then
  warn "verification failed — most likely the login didn't stick."
  warn "Re-run the wizard: services/hs-prices/setup.sh"
  exit 1
fi
sample_line=$(printf '%s\n' "$verify_out" | grep '^Sample:' || true)

say "Stopping the login browser…"
docker stop "$BROWSER_CONTAINER" >/dev/null 2>&1 || true
BROWSER_STARTED=0

finish

note "profile volume: $HS_PROFILE_DIR"
if [[ -n "$sample_line" ]]; then
  printf '  %sproof:%s %s\n' "$DIM" "$RESET" "$sample_line"
fi
note "when the HS session expires (every few weeks), re-run this wizard."
note "next: the spike reads the catalog via CHROME_CDP_URL in .env."
printf '\n'
